language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.5.1
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - pip install coveralls --use-mirrors
script:
    - coverage run --source=embed_video setup.py test
after_success:
    - coveralls
