language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
env:
    - DJANGO_VERSION=1.5.2
    - DJANGO_VERSION=1.6.5
install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install coveralls
    - pip install mock
    - pip install south
    - pip install nose
    - pip install testfixtures
script:
    - python setup.py build
    - PYTHONHASHSEED=0 python setup.py nosetests --verbosity 2 --with-coverage --cover-tests --cover-erase
after_success:
    - coveralls
