language: python
python:
    - "2.7"
    - "3.3"
env:
    - DJANGO_VERSION=1.5.2
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - pip install coveralls --use-mirrors
    - pip install mock --use-mirrors
    - pip install south --use-mirrors
script:
    - coverage run --source=embed_video setup.py test
after_success:
    - coveralls
